# Use root/example as user/password credentials
version: '3.1'

services:
  api:
    build: .
    ports:
      - 3000:3000
    depends_on: 
      - db

  db:
    image: mariadb
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: deploy
      MYSQL_PASSWORD: deploy
      MYSQL_DATABASE: backend