name: Node Github CI

on:
  push:
    branches:
      - david

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvkYPs4/+T+bG4ulEBPVs/Rnjfylu8j2WL+LA4gDGmcWITWGeVZnFcIqOpZUMdggYyi3jfklUKvThBtJUAZsTYST+35zsFtj5E68Q1f1aIx8KG/49tyJRCwOqkDW0/eDWxh2dv9q8ybdHyPvKQ6S6WBy9k1wLnle7wJN+QhWJ/+MAW+PO2lsNDk7XUUgmi9v5L6Hbe2lkNQVP8NElPt7ZHRuxhNTd2MgZo5Z/q4fbmuyiUSJXZjktPC/9/2fPNfYGNM9Hh/4hTZa6BpNt5z4lFw1nfFwS9j7SuRNiAIXy6r2CWB3bL+yHGpWxJLhkAUSWJP0Yl925jXRDyR95jHliNgLgHwkQyT9gVEnTbilXF2q4Gs8DQjunMNedEjoRBbCco/E31PDqQpzgsXQRtAoQmAnjz1NzUhhppIRIiAsi2aiGbFOSJuUJf4dyW1dv+hjJuqnApjp1apMbttk/AZfXQg0fPIH1S+WhqXuCCXfOtYsAW9ddjjS1YFEW0pZKhK1E= deploy@ubuntu-s-1vcpu-1gb-lon1-01
        port: 22
        script: |
          cd /home/deploy/lpiot/backend
          git pull origin david
          npm install --production
          npm build --production
          pm2 restart backend