name: Node Github CI

on:
  push:
    branches:
      - david

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd /home/deploy/lpiot/backend
          git pull origin david
          npm install --production
          npm build --production
          pm2 restart backend